// Auto-generated customization config - DO NOT EDIT MANUALLY
// This file is automatically generated when customization settings are saved
// Last generated: 2025-09-11T18:37:00.841Z

export const EMBEDDED_CUSTOMIZATION = {
  "headerBg": "#000000",
  "headerFontColor": "#ffffff",
  "sidebarBg": "#8d2020",
  "sidebarFontColor": "#ffffff",
  "logoBg": "#000000",
  "logoText": "Cabinets",
  "logoImage": "/assets/customization/logo.png",
  "loginLogo": "",
  "loginTitle": "Sign In",
  "loginSubtitle": "Enter your email and password to sign in!",
  "loginBackgroundColor": "#a21616",
  "showForgotPassword": false,
  "showKeepLoggedIn": true,
  "rightTitle": "Cabinets",
  "rightSubtitle": "Configure - Price - Quote",
  "rightTagline": "Dealer Portal",
  "rightDescription": "Manage end-to-end flow, from pricing cabinets to orders and returns with our premium sales automation software tailored to kitchen industry. A flexible and component-based B2B solution that can integrate with your existing inventory, accounting, and other systems.",
  "lastUpdated": "2025-09-11T18:37:00.841Z",
  "generatedAt": "2025-09-11T18:37:00.841Z"
}

export default EMBEDDED_CUSTOMIZATION