// Frontend customization configuration
// This file is automatically generated when customizations are saved
// DO NOT edit manually - changes will be overwritten

export const CUSTOMIZATION_CONFIG = {
  "logoText": "NJ Contractors",
  "logoImage": "/assets/customization/logo.jpg",
  "headerBg": "#000000",
  "headerFontColor": "#808080",
  "sidebarBg": "#000000",
  "sidebarFontColor": "#f5f5f5",
  "logoBg": "#0d0d0d",
  "companyName": "",
  "id": 1,
  "createdAt": "2025-09-22T19:51:25.000Z",
  "updatedAt": "2025-10-08T22:05:26.000Z",
  "_generated": "2025-10-09T03:03:04.844Z",
  "_version": "1.0.0"
}

export default CUSTOMIZATION_CONFIG
