// Frontend customization configuration
// This file is automatically generated when customizations are saved
// DO NOT edit manually - changes will be overwritten

export const CUSTOMIZATION_CONFIG = {
  "logoText": "NJ Cabinets Demo",
  "logoImage": "/assets/customization/logo.png",
  "headerBg": "#1E293B",
  "headerFontColor": "#F8FAFC",
  "sidebarBg": "#0F172A",
  "sidebarFontColor": "#E2E8F0",
  "logoBg": "#2563EB",
  "companyName": "",
  "id": 1,
  "createdAt": "2025-09-22T19:51:25.000Z",
  "updatedAt": "2025-09-23T00:24:24.000Z",
  "_generated": "2025-09-23T20:23:16.686Z",
  "_version": "1.0.0"
}

export default CUSTOMIZATION_CONFIG
