// Centralized lucide-react exports (React components)
// Use this module for lucide icons to avoid resolution ambiguity with CoreUI icons.
// Explicit imports/exports ensure Rollup doesn't drop alias re-exports in edge cases.
import {
  Search,
  Filter,
  Send,
  Pencil,
  Trash2,
  Settings,
  Users,
  User,
  ArrowLeft,
  X,
  Plus,
  Minus,
  Eye,
  EyeOff,
  Calendar,
  RefreshCw,
  List,
  Printer,
  Mail,
  Phone,
  MapPin,
  ExternalLink,
  Clipboard,
  History,
  Info,
  Clock,
  BarChart3,
  BriefcaseBusiness,
  LayoutGrid,
  CheckCircle,
  XCircle,
  ChevronUp,
  ChevronDown,
  Shield,
  LogOut,
  // Additional commonly used icons
  import {
    Factory,
    Edit3,
    Building2,
    FileText,
    SortAsc,
    SortDesc,
    
  } from

export {
  Search,
  Filter,
  Send,
  Pencil,
  Settings,
  Users,
  User,
  ArrowLeft,
  X,
  Plus,
  Minus,
  Eye,
  EyeOff,
  Calendar,
  List,
  Printer,
  Mail,
  Phone,
  MapPin,
  ExternalLink,
  Clipboard,
  History,
  Info,
  Clock,
  BarChart3,
  BriefcaseBusiness,
  LayoutGrid,
  CheckCircle,
  XCircle,
  ChevronUp,
  ChevronDown,
  Shield,
  LogOut,
  Factory,
  Edit3,
  Building2,
  FileText,
  SortAsc,
  SortDesc,
}

// Aliases with stable names used across the app
export const Trash = Trash2
export const Refresh = RefreshCw
export const BarChart = BarChart3
export const Briefcase = BriefcaseBusiness
