// Re-export commonly used icons for consistent imports (migrated from CoreUI to Lucide)
// This module provides CoreUI-named aliases for lucide-react icons to ease migration
export {
  Search as cilSearch,
  Trash2 as cilTrash,
  Pencil as cilPencil,
  Plus as cilPlus,
  User as cilUser,
  Settings as cilSettings,
  ExternalLink as cilExternalLink,
  File as cilFile,
  Clipboard as cilClipboard,
  Menu as cilMenu,
  X as cilX,
  CreditCard as cilCreditCard,
  DollarSign as cilMoney,
  DollarSign as cilDollar,
  CheckCircle as cilCheckCircle,
  Clock as cilClock,
  Ban as cilBan,
  Check as cilCheck,
  Save as cilSave,
  ArrowLeft as cilArrowLeft,
  // Navigation icons
  Cog as cilCog,
  Droplet as cilDrop,
  Puzzle as cilPuzzle,
  Gauge as cilSpeedometer,
  Calendar as cilCalendar,
  FolderOpen as cilFolderOpen,
  Users as cilPeople,
  Users as cilGroup,
  Bell as cilBell,
  FileText as cilNotes,
  MapPin as cilLocationPin,
  Calculator as cilCalculator,
  Brush as cilBrush,
  Factory as cilIndustry,
  MessageCircle as cilChatBubble,
  // Other commonly used icons
  Mail as cilEnvelopeClosed,
  Phone as cilPhone,
  Lock as cilLockLocked,
  UserPlus as cilUserPlus,
  Eye as cilEyedropper,
  Home as cilHome,
  Building as cilBuilding,
  Send as cilPaperPlane,
  MoreHorizontal as cilOptions,
  Copy as cilCopy,
  List as cilList,
  Briefcase as cilBriefcase,
  BarChart3 as cilChart,
  Contrast as cilContrast,
  MailOpen as cilEnvelopeOpen,
  Moon as cilMoon,
  Sun as cilSun,
  BellRing as cilBellExclamation,
  ChevronLeft as cilChevronLeft,
  ChevronRight as cilChevronRight,
  ArrowUp as cilSortAscending,
  ArrowDown as cilSortDescending,
  // Direct exports for common usage
  Pencil,
  Trash2,
  ChevronUp,
  ChevronDown
} from 'lucide-react';

// Export Trash as alias for Trash2 for backward compatibility
export { Trash2 as Trash } from 'lucide-react';
